---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: podinfo-dev
  namespace: dev
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: glob:dev-*
spec:
  releaseName: podinfo-dev
  chart:
    git: git@github.com:scottyhq/helm-operator-get-started
    path: charts/podinfo
    ref: master
  values:
    image: scottyhq/podinfo:dev-qrzjyo1i
    replicaCount: 1
    hpa:
      enabled: false
